on:
  push:
name: Build


jobs:
  build-win32:
    name: Build ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
            archive: zip
    steps:
      - uses: actions/checkout@master
      - name: Compile
        uses: rust-build/rust-build.action@master
        with:
          RUSTTARGET: ${{ matrix.target }}
          UPLOAD_MODE: none
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Binary ${{ matrix.target }}
          path: target/${{ matrix.target }}/deps/
          
  build-linux:
    name: Build ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        include:
          - target: x86_64-unknown-linux-musl
            archive: zip
    steps:
      - uses: actions/checkout@master
      - name: Compile
        uses: rust-build/rust-build.action@master
        with:
          RUSTTARGET: ${{ matrix.target }}
          UPLOAD_MODE: none
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Binary ${{ matrix.target }}
          path: target/${{ matrix.target }}/deps/
          
  build-osx:
    name: Build ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        include:
          - target: x86_64-apple-darwin
            archive: zip
    steps:
      - uses: actions/checkout@master
      - name: Compile
        uses: rust-build/rust-build.action@master
        with:
          RUSTTARGET: ${{ matrix.target }}
          UPLOAD_MODE: none
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Binary ${{ matrix.target }}
          path: target/${{ matrix.target }}/deps/
  build-wasm:
    name: Build ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        include:
          - target: wasm32-wasi
            archive: zip
    steps:
      - uses: actions/checkout@master
      - name: Compile
        uses: rust-build/rust-build.action@master
        with:
          RUSTTARGET: ${{ matrix.target }}
          UPLOAD_MODE: none
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Binary ${{ matrix.target }}
          path: target/${{ matrix.target }}/deps/
